config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :pins
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'mypins' => 'pins#mypins'
  get 'pinsof/:user_id' => 'pins#pinsof', :as => "pinsof"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  validates :photo, presence:true
  validates :description, presence:true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :phone])

  end


end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:index, :show]
  # GET /pins
  # GET /pins.json
  def pinsof
    @user_id = params[:user_id]
    @user = User.find(@user_id)
    @pins = @user.pins
  end

  def mypins
    @pins = current_user.pins
  end

  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
    @pins = current_user.pins #agregar   @pins = current_user.pins

  end

  # GET /pins/1/edit
  def edit
    @pins = current_user.pins #agregar  @pins = current_user.pins
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)
    #@pins = current_user.pins
    @pin.user_id = current_user.id

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:photo, :description, :name, :user_id) #agregar :user_id
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyPinterest</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


    <%= stylesheet_link_tag    '/assets/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag '/assets/application', 'data-turbolinks-track': 'reload' %>



    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<!-- Cargar la libreria de Masonry-->


      <script type="text/javascript" src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.js"></script>



  </head>

  <body>

    <%= render 'shared/navbar' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_with(model: pin, local: true) do |form| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="form-group">
      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name,  :class=> 'form-control' %>
      </div>
    </div>
<div class="form-group">
  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo, id: :pin_photo, :class=> 'form-control' %>
  </div>
</div>
    <div class="form-group">
  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :pin_description, :class=> 'form-control' %>
  </div>
</div>
<!-- agregar este div para arreglar lo de crear pins-->
    <div class="form-group">
      <div class="field">
        <% @pins.each do |pin| %>
         <%= hidden_field_tag :user_id, pin.user.id %>
            <%= form.hidden_field :user_id, value: pin.user.id %>

            <% end %>

      </div>
    </div>



    <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="container">
  <h1>Editar el Pin</h1>
<div class="row">
  <div class="col-md-6">
<%= render 'form', pin: @pin %>
  </div>
</div>
<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>
</div>

app/views/pins/index.html.erb
<h1>Listing pins</h1>
<!--<p id="notice"><%= notice %></p> -->


<div id="container">

  <% @pins.each do |pin| %>
      <div class="col-md-3" style="width: 25%">
        <div class="thumbnail">
          <%= pin.name %>
          <%= image_tag( pin.photo, :class => 'img-responsive') %>
          <%= pin.description %>
          <div class="buttons", style="margin-top:10px; margin-bottom:10px ">
            <%= link_to 'Show', pin , :class => 'btn'%>
            <%= link_to 'Edit', edit_pin_path(pin), :class => 'btn' %>
            <% if user_signed_in? %>
                <%= link_to 'Destroy', pin, :method=> :delete, data: { confirm: 'Are you sure?' }, :class => 'btn'  %>
            <% end %>
          </div>
        </div>
      </div>
  <% end %>
  <br>
  <% if user_signed_in? %>
      <%= link_to 'New Pin', new_pin_path %>
  <% end %>
</div>


<script type="text/javascript">
    var $container = $('#container')
        // options
        $container.masonry({
        columnWidth: 200,
        itemSelector: '.item'
    });

  $(window).load(function(){
    var $container = $('#container');
        // options
      $container.masonry({
          columnWidth: 200,
          itemSelector: '.item'
    });
  })
</script>

app/views/pins/mypins.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Mis Pins</h1>
  <% @pins.each do |pin| %>
      <div class="col-md-3">
        <div class="thumbnail">
          <%= pin.name %>
          <%= image_tag( pin.photo, :class => 'img-responsive') %>
          <%= pin.description %>
          <div class="buttons", style="margin-top:10px; margin-bottom:10px ">
            <%= link_to 'Show', pin , :class => 'btn'%>
            <%= link_to 'Edit', edit_pin_path(pin), :class => 'btn' %>
            <% if user_signed_in? %>
                <%= link_to 'Destroy', pin, :method=> :delete, data: { confirm: 'Are you sure?' }, :class => 'btn'  %>
            <% end %>
          </div>
        </div>
      </div>
  <% end %>
  <br>
  <% if user_signed_in? %>
      <%= link_to 'New Pin', new_pin_path %>
  <% end %>
</div>

app/views/pins/new.html.erb
<div class="container">
<h1>Crear nuevo pin</h1>
<div class="col-md-6">
  <div  class="row">
<%= render 'form', pin: @pin, pins: @pins %> <!-- agregar  pins: @pins -->
</div>
<%= link_to 'Back', pins_path %>
</div>
</div>

app/views/pins/pinsof.html.erb
<%= @user_id %>

<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Mis Pins</h1>
  <% @pins.each do |pin| %>
      <div class="col-md-3">
        <div class="thumbnail">
          <%= pin.name %>
          <%= image_tag( pin.photo, :class => 'img-responsive') %>
          <%= pin.description %>
          <div class="buttons", style="margin-top:10px; margin-bottom:10px ">
            <%= link_to 'Show', pin , :class => 'btn'%>
            <%= link_to 'Edit', edit_pin_path(pin), :class => 'btn' %>
            <% if user_signed_in? %>
                <%= link_to 'Destroy', pin, :method=> :delete, data: { confirm: 'Are you sure?' }, :class => 'btn'  %>
            <% end %>
          </div>
        </div>
      </div>
  <% end %>
  <br>
  <% if user_signed_in? %>
      <%= link_to 'New Pin', new_pin_path %>
  <% end %>
</div>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @pin.name %>
</p>
<p>
  <strong>Photo:</strong>
  <%= image_tag(@pin.photo, :style =>'width:200px') %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>

<%= link_to "Mas pins del mismo usuario", pinsof_path(@pin.user.id) %>

app/views/shared/_navbar.html.erb

<nav class="navbar navbar-default " role="navigation" style="margin-bottom:0px;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <a class="navbar-brand" href="<%= welcome_index_path %>">My Pinteres</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="">Nosotros <span class="sr-only">(current)</span></a></li>
        <li><a href="<%= mypins_path %>">Mis Pins</a> </li>
        <li><a href="<%= pins_path %>">Pins</a></li>

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user.nil? %>
          <li><a href="<%= new_user_session_path %>">Ingreso</a></li>
          <li><a href="<%= new_user_registration_path %>">Registro</a></li>
        <% else %>
        <li><a href="<%= destroy_user_session_path %>" data-method="delete">Salir</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <div class="container">
    <p>Información de los mejores clanes</p>
    <h1 class="titulo">Lo Mejor de Naruto Shippuden</h1>
    <a href="www.zonarutoppuden.com/2010/10/naruto-shippuden-capitulos.html" target="_blank" class="btn btn-default">
      Ver los episodios
      <span class="glyphicon glyphicon-eye-open" style=" color:green"></span>
    </a>
  </div>
</div>
<div class="container">
  <div class="row">

    <div class="col-md-4">
      <div class="page-header">
        <h2 style="display:inline">Clan Uzumaki</h2>
        <span class="label label-default">New</span>
      </div>
     <!-- <a href="">Ve los episodios</a> -->
     <!-- <a href="http://en1mes.com" target="_blank">En1Mes</a> -->
      <p>
        El Clan Uzumaki (うずまき一族, Uzumaki Ichizoku) fue un prominente clan de Uzushiogakure.
        Eran parientes lejanos del Clan Senju y por lo tanto ambos clanes estaban en buenos términos, una alianza
        que se extendía a sus aldeas ocultas - Konohagakure y Uzushiogakure.
        Los Shinobis de Konoha aun utilizan el símbolo de Uzushiogakure en sus chalecos, así como sobre los hombros de sus uniformes
        como señal de la amistad y buena voluntad entre los dos pueblos, y continuá haciéndolo hasta hoy,
        en recuerdo de su amistad e incluso años después de la destrucción de Uzushiogakure.
        <img src="http://pm1.narvii.com/6043/ad1aa1066f5d371f3a81042ea9aa45e523dc4943_hq.jpg"  class="img-responsive">
      </P>

      <div class="page-header">
        <h2>Clan Hyuga</h2>
      </div>
      <p>
        El Clan Hyūga (日向一族, Hyūga Ichizoku) es uno de los cuatro clanes nobles de Konohagakure.
        Todos los miembros de este clan poseen desde el nacimiento su Kekkei Genkai, el Byakugan que
        les otorga una visión aumentada y la capacidad de ver a través de objetos sólidos, a parte de poder
        ver el Sistema de Circulación de Chakra. Los miembros de este clan poseen la habilidad única de expulsar
        Chakra de cualquiera de sus Tenketsu.
        <img src="http://pm1.narvii.com/6297/e8f93de447fff2afd34c92eef34ac52eda6a7a66_hq.jpg" class="img-responsive">
      </p>

    </div>


    <div class="col-md-4">
      <div class="page-header">
        <h2>Clan Uchiha</h2>
      </div>
      <p>El Clan Uchiha, también conocido como Clan del Sharingan es uno de los clanes más poderosos junto al Clan Senju.
        Debido a sus grandes habilidades en todos los tipos de combates se ganaron el apodo de el Clan de la Guerra.
        Los Uchihas son descendientes del hijo mayor del Sabio de los Seis Caminos, dicho ancestro tenía la idea de que
        el "poder" era la única forma de conseguir la paz que su padre deseaba. Sin embargo el Rikudō eligió a su hijo menor
        como el que heredaría su legado ya que creía que el "amor" era la forma de conseguir la paz, pero esta decisión fue tomada
        mal por su hermano mayor ya que se enfrentó a su propio hermano para recuperar lo que consideraba suyo, desde ese momento se
        formó lo que se conoce como La Maldición del Odio. Los descendientes del hijo menor serían los Senju, causando que se formara
        una rivalidad entre los Uchiha y los Senjus.
        <img src="http://pm1.narvii.com/5780/a2d9c2b99715c360ab3a66827dd35161f504f09f_hq.jpg"  class="img-responsive">
      </P>
    </div>

    <div class="col-md-4">
      <div class="page-header">
        <h2>Clan Ōtsutsuki</h2>
      </div>
      <p>
        El Clan Ōtsutsuki (大筒木一族, Ōtsutsuki Ichizoku) es un clan de seres alienígenas que llegaron a la Tierra aproximadamente hace unos 1.000 años.
        Los Ōtsutsuki tuvieron una gran influencia en la humanidad, comenzando la historia de los Shinobis.
        Al ser los ancestros de todos los Shinobis, son los progenitores de clanes notables en el mundo como el Senju, Uchiha, Hyūga, Uzumaki y Kaguya.
        Por otro lado los Ōtsutsuki de la Luna fueron los creadores de las Marionetas y por lo tanto de su utilización en combate.
        <img src="https://i.ytimg.com/vi/Cr2bcI-U3ZA/maxresdefault.jpg" class="img-responsive">
        </P>
    </div>

    <div class="col-md-4">
      <div class="page-header">
        <h2>Clan Senju</h2>
      </div>
      <p>
        El Clan Senju (千手一族, Senju Ichizoku) también conocido como El Clan de las Mil Habilidades (千の手を持つ一族, Sen no te o Motsu Ichizoku)
        o el Clan Senju del Bosque (森の千手一族, Mori no Senju Ichizoku) fue considerado el clan más poderoso del mundo shinobi durante
        la Era de Guerra entre Clanes, durante este tiempo sostuvo una ardua rivalidad con el Clan Uchiha quien era el único que podía
        medirse con ellos. Ambos clanes eran rivales y sostenían batallas feroces, pero posteriormente decidieron aliarse y formar Konohagakure.
        Son parientes lejanos del Clan Uzumaki.
        <img src="https://i.ytimg.com/vi/BEtg4Ieu6T8/hqdefault.jpg" class="img-responsive">
      </p>
    </div>



      <!--
      <a href="https://www.acmilan.com/en">
        <img src="" >
      </a>
      <hr>
      <br> -->
<!--
      <img src="">
      <ul>
        <li>Item 1</li>
        <li>Item 2</li>
        <li>Item 3</li>
      </ul> -->
    </div>
  </div>